### ISSUE TITLE
unable to complete sale, throwing error unknown column chnage_amount

### ISSUE THREAD

**Issue by eramudeep** [chrisidakwo/EFLInventory-V2#10]
**unable to complete sale, throwing error** 
![image](https://user-images.githubusercontent.com/38516686/60301627-7c657200-994f-11e9-83ea-c8b47fa7ef4e.png)

**Comment by yaisuarez** [comment]
not on click help me
<button class="btn btn-success pull-right sell-button d-none">
                        Sell Products<i class="mdi mdi-arrow-right-bold pl-2"></i>
                    </button>
