### ISSUE TITLE
Which Laravel/PHP version would work on this? 

### ISSUE THREAD

**Issue by percydeleon** [chrisidakwo/EFLInventory-V2#3]
Hello, I am using PHP 7.2 - am I missing something? 

![image](https://user-images.githubusercontent.com/1147561/48933803-91eb6700-ef3c-11e8-913a-122f660855df.png)

**Comment by chrisidakwo** [comment]
PHP 7.2 is fine. Have a look at the `composer.json` file, it was built with PHP 7, and Laravel 5.5.

However, the error you're seeing has been fixed. The error shows because you do not yet have products in your DB.
