### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by bajwha** [chrisidakwo/EFLInventory-V2#4]
Hi I am getting this error
Fatal error: Uncaught Error: Call to a member function make() on array in D:\xampp\htdocs\p2\eflinventory-v2\artisan:33
Stack trace:
#0 {main}
  thrown in D:\xampp\htdocs\p2\eflinventory-v2\artisan on line 33
Script @php artisan package:discover handling the post-autoload-dump event returned with error code 255

please help

**Comment by chrisidakwo** [comment]
Firstly, have you installed your composer packages? Secondly, what were you trying to do that got you there? A screenshot of the error stack trace will also help.
