### ISSUE TITLE
Composer Install returns error

### ISSUE THREAD

**Issue by stanyjude** [chrisidakwo/EFLInventory-V2#5]
Ubuntu 16.04
Php 7.2
MySql and Apache installed and working

I ran 
1. git clone https://github.com/chrisidakwo/eflinventory-v2.git
2. cd eflinventory-v2
3. composer install

Error : 
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

                                                
  [Exception]                                   
  Unable to load the "app" configuration file.  
                                                

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1
![screenshot from 2019-03-05 20-08-21](https://user-images.githubusercontent.com/26185345/53812915-73a4f680-3f82-11e9-81ec-b0ad831b3901.png)

**Comment by suryasun** [comment]
me too

**Comment by chrisidakwo** [comment]
Sorry guys, I'm sure you must gotten the fix needed. I think I mistakenly ignored the app.php file. I'll make the necessary change. In the meantime, should any one have similar issues, please copy the content here, create a new `app.php` file within the `config` directory and paste the copied content into the new file: 
[https://raw.githubusercontent.com/chrisidakwo/EFLInventory-V2/heroku/config/app.php](app.php)

Sorry for this, quite lame if you ask me. I'll fix it and update ASAP.
