### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by IssakaBaba** [chrisidakwo/EFLInventory-V2#6]
Every other step was successful till here...

C:\wamp64\www\EFLInventory-V2>php artisan key:generate

  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Type error: Argument 2 passed to Illuminate\Routing\UrlGenerator::__construct() must be an instance of Illuminate\Http\Request, null given, called in C:\wamp64\www
  \EFLInventory-V2\vendor\laravel\framework\src\Illuminate\Routing\RoutingServiceProvider.php on line 67

![Screenshot (7)](https://user-images.githubusercontent.com/37392028/55322558-8cff6c80-5474-11e9-95ed-7d279a3801b8.png)

**Comment by chrisidakwo** [comment]
Sorry, I've been away for a while. Please ensure you have the `app.php` file within the `config` directory. Here is a link to the file: [https://github.com/chrisidakwo/EFLInventory-V2/blob/heroku/config/app.php](app.php)

I'm sorry I somehow ignored the file with git, and didnt even realize it.

I'll update it ASAP. In the meantime, visit the link above, copy the content of the file and create a file named `app.php` within the `config` directory. Try running your artisan commands again.

**Comment by IssakaBaba** [comment]
Its is operating now but I got this after I logged in



![Screenshot (8)](https://user-images.githubusercontent.com/37392028/55971417-56e29980-5c79-11e9-8219-8653c88d8876.png)

**Comment by chrisidakwo** [comment]
Please run the application using the artisan command `php artisan serve`

Once done, access from `http://localhost:8000`

If the port is not free, do something like this: `php artisan serve --port 8900` Access from `http://localhost:8900`
