### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by IssakaBaba** [chrisidakwo/EFLInventory-V2#7]
Please I get this error when I login. The php artisan serve runs successfully though.

![Screenshot (9)](https://user-images.githubusercontent.com/37392028/56005375-e9118e80-5cc7-11e9-9204-85278b527f8c.png)

**Comment by IssakaBaba** [comment]
And at one point I'm getting an error saying "Your login credentials do not match our records"

**Comment by chrisidakwo** [comment]
Please can I see what your database config file looks like? Especially the msyql config block. Also your .env file - where you set the DB connection.

**Comment by euclimauro** [comment]
After database configuration, I'm trying to login using the same credentials and I'm been redirected to the same page, I'm unable to pass the login fase..

**Comment by euclimauro** [comment]
[env.txt](https://github.com/chrisidakwo/EFLInventory-V2/files/3145513/env.txt)

**Comment by chrisidakwo** [comment]
Are you using the password and login I specified [here](https://github.com/chrisidakwo/EFLInventory-V2#setup)? If you are, then I think this error might be due to your mysql setup.

When I said database config file I meant the `database.php` file within the `config` directory.  

By the way, its the exact same app I have running here: [https://eflinventory.herokuapp.com/](https://eflinventory.herokuapp.com/)

**Comment by chrisidakwo** [comment]
I want to help you solve this but I don't have enough details to understand your setup and what might be wrong on your end.
What system are you running this on? What's the PHP version? What's the MySQL version?

Look for the error log file within the `storage` directory. Try logging in and share the error that might get dumped there. Or take a screenshot if there's an error page like the image above.

**Comment by euclimauro** [comment]
[database.txt](https://github.com/chrisidakwo/EFLInventory-V2/files/3154344/database.txt)
These is my database file,  I'm using PHP 7.1.23 and mysql 8.0.16 and the logs, there is no error when entered the same credentials, I'm using Laravel 5.8..
[logs.log](https://github.com/chrisidakwo/EFLInventory-V2/files/3154354/logs.log)

**Comment by euclimauro** [comment]
I downloaded again, running composer install  it's generating the error below:
![Screenshot 2019-05-07 at 9 07 27 PM](https://user-images.githubusercontent.com/15140631/57329817-659f5d80-710c-11e9-98fe-4761c2092663.png)

**Comment by euclimauro** [comment]
can you guys help me on these..
