### ISSUE TITLE
Error Artisan

### ISSUE THREAD

**Issue by euclimauro** [chrisidakwo/EFLInventory-V2#8]
I'm trying to run the command php artisan migrate a it's generating these error bellow:

   Illuminate\Database\QueryException  : SQLSTATE[HY000] [2002] No such file or directory (SQL: select * from information_schema.tables where table_schema = inventory and table_name = migrations)

  at /Users/euclidesmauro/code/Laravel/vmce/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664
    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668|

  Exception trace:

  1   PDOException::("SQLSTATE[HY000] [2002] No such file or directory")
      /Users/euclidesmauro/code/Laravel/vmce/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:70

  2   PDO::__construct("mysql:unix_socket=/var/run/mysqld/mysqld.sock;dbname=inventory", "root", "Admin@dev2019!", [])
      /Users/euclidesmauro/code/Laravel/vmce/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:70

  Please use the argument -v to see more details.

I don't understand why, cause my .env file is ok, I have configured the Database.php as well, do you have any idea why?

**Comment by euclimauro** [comment]
These error occur when I try to migrate the database using the command: php artisan migrate

**Comment by chrisidakwo** [comment]
This is an issue with your MySQL setup for the app, I think. Please have a look at this link : [https://stackoverflow.com/questions/20723803/pdoexception-sqlstatehy000-2002-no-such-file-or-directory](https://stackoverflow.com/questions/20723803/pdoexception-sqlstatehy000-2002-no-such-file-or-directory). Go through the suggested solutions, see which one works for you.

If none, please let me know. But I think one of those should solve it for you.

**Comment by euclimauro** [comment]
Thanks a lot for you patience.. I manage it by downgrading my mysql version!.

**Comment by chrisidakwo** [comment]
Oh good, thank you for updating that!
